### POST create

POST http://localhost:3000/products.json
Content-Type: application/json

{
    "name": "orange juice",
    "price": 5.99,
    "image_url": "",
    "description": "very fresh and replenishing",
    "inventory": 1,
    "supplier_id": 1
}

### GET index

GET http://localhost:3000/products.json


### GET show

GET http://localhost:3000/products/2.json

### PATCH update

PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{
    "name": "Socks",
    "price": -5.99,
    "description": "only comes one side!"
}

### DELETE destory
DELETE http://localhost:3000/products/12

##############################################

### Supplier index

get http://localhost:3000/suppliers

### Supplier show

get http://localhost:3000/suppliers/1

### Supplier create

post http://localhost:3000/suppliers
Content-Type: application/json

{
    "name": "",
    "email": "",
    "phone_number": "",
    "supplier_id": 
}

### Supplier update

patch http://localhost:3000/suppliers/1
Content-Type: application/json

{

}

### Supplier destroy

delete http://localhost:3000/suppliers/1


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}