### POST create

POST http://localhost:3000/products.json
Content-Type: application/json

{
    "name": "orange juice",
    "price": 5.99,
    "image_url": "",
    "description": "very fresh and replenishing",
    "inventory": 1,
    "supplier_id": 1
}

### GET index

GET http://localhost:3000/products.json


### GET show

GET http://localhost:3000/products/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA


### PATCH update

PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{
    "name": "Socks",
    "price": -5.99,
    "description": "only comes one side!"
}

### DELETE destory
DELETE http://localhost:3000/products/12

#--------------------------------------------------------------------

### Supplier index

get http://localhost:3000/suppliers

### Supplier show

get http://localhost:3000/suppliers/1

### Supplier create

post http://localhost:3000/suppliers
Content-Type: application/json

{
    "name": "",
    "email": "",
    "phone_number": "",
    "supplier_id": 
}

### Supplier update

patch http://localhost:3000/suppliers/1
Content-Type: application/json

{

}

### Supplier destroy

delete http://localhost:3000/suppliers/1

#-------------------------------------------------------------------

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name1",
  "email": "test1@test.com",
  "password": "password",
  "password_confirmation": "password"
}

#--------------------------------------------------------------------

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

#--------------------------------------------------------------------

### ORDER create
post http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTI4OTE2NDF9.ilAG65roXdKXtAlmH6Ju2YifOuTOuYNBs3jeJ_qlsIM

{
  
  "product_id": 8,
  "quantity": 2

                                      
}             
     
### ORDER index
get http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTI4OTY1NzR9.2k5FZwKFc4s3wUZVu_RP4of3UoURlKYbdOHJZBFrWjs

### ORDER show
get http://localhost:3000/orders/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTI4OTY1NzR9.2k5FZwKFc4s3wUZVu_RP4of3UoURlKYbdOHJZBFrWjs




