### POST create

POST http://localhost:3000/products.json
Content-Type: application/json

{
    "name": "orange juice",
    "price": 5.99,
    "image_url": "",
    "description": "very fresh and replenishing"
}

### GET index

GET http://localhost:3000/products.json


### GET show

GET http://localhost:3000/products/2.json

### PATCH update

PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{
    "name": "Socks",
    "price": -5.99,
    "description": "only comes one side!"
}

### DELETE destory
DELETE http://localhost:3000/products/7